/**
 * seed_sqlite.cjs - Seeds ALL 120 SDLC + 10 AMS questions into the local SQLite DB
 * Run: node seed_sqlite.cjs
 */
const Database = require('better-sqlite3');
const path = require('path');

const DB_PATH = path.join(__dirname, 'sdlc_local.db');
const db = new Database(DB_PATH);

// ─── 120 SDLC Questions ─────────────────────────────────────────────────────
const SDLC_QUESTIONS = [
  // Requirements (18)
  { id:1,  area:'Requirements', subArea:'Product Discovery & Ideation',              practice:'Idea generation & exploration',                              questionText:'To what extent does your team use AI for idea generation & exploration?' },
  { id:2,  area:'Requirements', subArea:'Product Discovery & Ideation',              practice:'Problem discovery & framing',                                questionText:'To what extent does your team use AI for problem discovery & framing?' },
  { id:3,  area:'Requirements', subArea:'Requirement Engineering',                   practice:'Requirements elicitation and analysis',                       questionText:'To what extent does your team use AI for requirements elicitation and analysis?' },
  { id:4,  area:'Requirements', subArea:'Requirement Engineering',                   practice:'Technical feasibility and risk assessment',                   questionText:'To what extent does your team use AI for technical feasibility and risk assessment?' },
  { id:5,  area:'Requirements', subArea:'Requirement Prioritization & Road-mapping', practice:'Dependency & sequencing analysis',                            questionText:'To what extent does your team use AI for dependency & sequencing analysis?' },
  { id:6,  area:'Requirements', subArea:'Requirement Prioritization & Road-mapping', practice:'Requirement prioritization & trade-off analysis',             questionText:'To what extent does your team use AI for requirement prioritization & trade-off analysis?' },
  { id:7,  area:'Requirements', subArea:'Requirement Prioritization & Road-mapping', practice:'Roadmap scenario planning',                                   questionText:'To what extent does your team use AI for roadmap scenario planning?' },
  { id:8,  area:'Requirements', subArea:'Requirements',                              practice:'Backlog Refinement',                                          questionText:"To what extent is the following true in your current practice: AI decomposes vague backlog items into sized features with acceptance criteria. The engineer's role is to judge and adjust AI output, not to write stories from a blank page." },
  { id:9,  area:'Requirements', subArea:'Requirements',                              practice:'Bidirectional Traceability',                                  questionText:"To what extent is the following true in your current practice: The agent maintains and enforces traceability automatically on every PR. The engineer sets the traceability policy once; the agent applies it continuously without prompting." },
  { id:10, area:'Requirements', subArea:'Requirements',                              practice:'Effort, Cost & Risk Simulation',                              questionText:"To what extent is the following true in your current practice: The agent monitors cost and risk continuously against thresholds the team has set, and alerts automatically when they are breached. Humans are not periodically reviewing a spreadsheet - the system comes to them." },
  { id:11, area:'Requirements', subArea:'Requirements',                              practice:'Impact Analysis',                                             questionText:"To what extent is the following true in your current practice: An agent independently traces a change request across the codebase and produces an impact matrix. The engineer validates the output - they do not do the tracing themselves." },
  { id:12, area:'Requirements', subArea:'Requirements',                              practice:'OCM & Course Correction',                                     questionText:"To what extent is the following true in your current practice: The system catches scope or risk drift and raises it before a human notices. If a human is always the one spotting drift, this practice is not Achieved." },
  { id:13, area:'Requirements', subArea:'Requirements',                              practice:'Root-to-Live Discovery & Sequencing',                         questionText:"To what extent is the following true in your current practice: When scope changes, the system replans automatically and escalates only when sequencing decisions exceed defined risk thresholds. A human does not replan by hand - they approve or override the agent's plan." },
  { id:14, area:'Requirements', subArea:'Requirements',                              practice:'Transcript → Requirements',                                   questionText:"To what extent is the following true in your current practice: The first draft of every requirement comes from AI processing meeting notes or transcripts - not from a human writing from scratch. The engineer directs, refines, and approves; authoring is AI's job." },
  { id:15, area:'Requirements', subArea:'User Experience & Insights',                practice:'Experience pain-point identification',                         questionText:'To what extent does your team use AI for experience pain-point identification?' },
  { id:16, area:'Requirements', subArea:'User Experience & Insights',                practice:'Feedback & sentiment analysis',                               questionText:'To what extent does your team use AI for feedback & sentiment analysis?' },
  { id:17, area:'Requirements', subArea:'User Experience & Insights',                practice:'Persona & journey modeling',                                  questionText:'To what extent does your team use AI for persona & journey modeling?' },
  { id:18, area:'Requirements', subArea:'User Experience & Insights',                practice:'User research synthesis',                                     questionText:'To what extent does your team use AI for user research synthesis?' },

  // Architecture (16)
  { id:19, area:'Architecture', subArea:'Architecture',                              practice:'Architecture Synthesiser',                                    questionText:"To what extent is the following true in your current practice: An agent produces target-state blueprint options with trade-off analysis. The architect selects and approves a direction - they do not synthesise options themselves. The agent does the synthesis work." },
  { id:20, area:'Architecture', subArea:'Architecture',                              practice:'Auto-Generate Architecture Diagrams',                          questionText:"To what extent is the following true in your current practice: The first version of any architecture diagram is AI-generated from code, IaC, or natural language. An engineer directing AI to produce a diagram, then refining it, is the standard workflow - not an engineer drawing from scratch." },
  { id:21, area:'Architecture', subArea:'Architecture',                              practice:'Automated Drift Remediation',                                  questionText:"To what extent is the following true in your current practice: Low-risk drift is remediated and shipped automatically when tests pass and the change meets defined guardrails. Humans are only pulled in when the drift is high-risk or the guardrails cannot classify it. Humans set the guardrails - the agent enforces them." },
  { id:22, area:'Architecture', subArea:'Architecture',                              practice:'Compliance & Security Policy Advisor',                         questionText:"To what extent is the following true in your current practice: The system notices a compliance gap before a person does and raises it automatically. If a human is the one discovering policy violations, the monitoring is not at this level." },
  { id:23, area:'Architecture', subArea:'Architecture',                              practice:'Drift Detection in PRs',                                       questionText:"To what extent is the following true in your current practice: The agent inspects every PR for architecture drift and can block a clear violation without a human stepping in. If a human must read every PR to catch drift, the gate is not real." },
  { id:24, area:'Architecture', subArea:'Architecture',                              practice:'Extract Architecture from Code',                               questionText:"To what extent is the following true in your current practice: AI reads the codebase and generates architecture documentation and component maps. Engineers do not draw diagrams from memory - they review and correct AI-generated output. Critically, the AI can see the actual codebase, not just generic knowledge." },
  { id:25, area:'Architecture', subArea:'Architecture',                              practice:'FinOps Modeller & Planner',                                    questionText:"To what extent is the following true in your current practice: The agent flags architecture cost implications and overspend automatically against thresholds the team has set. Cost decisions are not discovered in a monthly review - the system surfaces them in real time." },
  { id:26, area:'Architecture', subArea:'Architecture & Design Governance',          practice:'Architecture & Design Quality Governance',                     questionText:'To what extent does your team use AI for architecture & design quality governance?' },
  { id:27, area:'Architecture', subArea:'Architecture & Design Governance',          practice:'Architecture Decision Governance & Traceability',              questionText:'To what extent does your team use AI for architecture decision governance & traceability?' },
  { id:28, area:'Architecture', subArea:'Architecture & Design Governance',          practice:'Architecture Decision Knowledge management',                   questionText:'To what extent does your team use AI for architecture decision knowledge management?' },
  { id:29, area:'Architecture', subArea:'Architecture & Design Governance',          practice:'Architecture Decision Review & Approval Governance',           questionText:'To what extent does your team use AI for architecture decision review & approval governance?' },
  { id:30, area:'Architecture', subArea:'Architecture & Design Governance',          practice:'Architecture and design reviews',                              questionText:'To what extent does your team use AI for architecture and design reviews?' },
  { id:31, area:'Architecture', subArea:'Architecture & Design Governance',          practice:'Candidate Architecture Generation',                            questionText:'To what extent does your team use AI for candidate architecture generation?' },
  { id:32, area:'Architecture', subArea:'Architecture & Design Governance',          practice:'Decision traceability',                                        questionText:'To what extent does your team use AI for decision traceability?' },
  { id:33, area:'Architecture', subArea:'Architecture & Design Governance',          practice:'Design Documentation Governance & Traceability (or) Design Traceability Management', questionText:'To what extent does your team use AI for design documentation governance & traceability (or) design traceability management?' },
  { id:34, area:'Architecture', subArea:'Legacy Modernization & Decomposition',      practice:'System Decomposition Analysis',                                questionText:'To what extent does your team use AI for system decomposition analysis?' },

  // Development (29)
  { id:35, area:'Development',  subArea:'Build Process Management',                  practice:'Build Artifact generation and storage',                        questionText:'To what extent does your team use AI for build artifact generation and storage?' },
  { id:36, area:'Development',  subArea:'Build Process Management',                  practice:'Build Automation Engineering',                                  questionText:'To what extent does your team use AI for build automation engineering?' },
  { id:37, area:'Development',  subArea:'Build Process Management',                  practice:'Build Execution',                                               questionText:'To what extent does your team use AI for build execution?' },
  { id:38, area:'Development',  subArea:'Build Process Management',                  practice:'Build Failure Management',                                      questionText:'To what extent does your team use AI for build failure management?' },
  { id:39, area:'Development',  subArea:'Build Process Management',                  practice:'Build performance optimization',                                 questionText:'To what extent does your team use AI for build performance optimization?' },
  { id:40, area:'Development',  subArea:'Code Development & Review',                 practice:'Code Branching & Merge Governance',                             questionText:'To what extent does your team use AI for code branching & merge governance?' },
  { id:41, area:'Development',  subArea:'Code Development & Review',                 practice:'Code Generation',                                               questionText:'To what extent does your team use AI for code generation?' },
  { id:42, area:'Development',  subArea:'Code Development & Review',                 practice:'Code Quality Standards Governance & Enforcement',               questionText:'To what extent does your team use AI for code quality standards governance & enforcement?' },
  { id:43, area:'Development',  subArea:'Code Development & Review',                 practice:'Code Review',                                                   questionText:'To what extent does your team use AI for code review?' },
  { id:44, area:'Development',  subArea:'Code Development & Review',                 practice:'Code base Management',                                          questionText:'To what extent does your team use AI for code base management?' },
  { id:45, area:'Development',  subArea:'Code Development & Review',                 practice:'Code refactoring and optimization',                              questionText:'To what extent does your team use AI for code refactoring and optimization?' },
  { id:46, area:'Development',  subArea:'Code Development & Review',                 practice:'Defect prevention and resolution',                              questionText:'To what extent does your team use AI for defect prevention and resolution?' },
  { id:47, area:'Development',  subArea:'Code Development & Review',                 practice:'Security Vulnerability',                                        questionText:'To what extent does your team use AI for security vulnerability?' },
  { id:48, area:'Development',  subArea:'Configuration & Dependency Management',     practice:'Configuration file management',                                  questionText:'To what extent does your team use AI for configuration file management?' },
  { id:49, area:'Development',  subArea:'Configuration & Dependency Management',     practice:'Dependency management',                                          questionText:'To what extent does your team use AI for dependency management?' },
  { id:50, area:'Development',  subArea:'Configuration & Dependency Management',     practice:'Source & Version Management Governance',                        questionText:'To what extent does your team use AI for source & version management governance?' },
  { id:51, area:'Development',  subArea:'Development',                               practice:'AI Coding Assistant - Agent Mode',                               questionText:"To what extent is the following true in your current practice: Every engineer uses AI in agent mode for multi-step tasks - not just autocomplete. If removing AI tools would only affect speed and leave the process unchanged, this is the level the team is at." },
  { id:52, area:'Development',  subArea:'Development',                               practice:'AI-Assisted Code Review',                                        questionText:"To what extent is the following true in your current practice: AI participates in every code review, flagging bugs and security issues. A human reads every flag and makes the final call - the AI accelerates the reviewer, it does not replace the human gate." },
  { id:53, area:'Development',  subArea:'Development',                               practice:'Custom Agents via MCP & Scripts',                               questionText:"To what extent is the following true in your current practice: An agent can open a pull request on its own without a human writing the change by hand. The human's role is to review and approve the PR - not to author the code. This is the line between L1 and L2." },
  { id:54, area:'Development',  subArea:'Development',                               practice:'Custom Instructions & Skills',                                   questionText:"To what extent is the following true in your current practice: AI can see the team's own codebase, standards, and project context - not just generic public knowledge. Custom instructions or skills are in place so the agent is project-aware by default, not by the engineer pasting context manually each time." },
  { id:55, area:'Development',  subArea:'Development',                               practice:'Long-Running Agentic Tasks',                                     questionText:"To what extent is the following true in your current practice: Agents operate autonomously over extended periods. The safety net - automated rollback, fast catch-and-undo - is what makes this level achievable. If a wrong agent action cannot be caught and reversed quickly, the team cannot safely operate here." },
  { id:56, area:'Development',  subArea:'Development',                               practice:'Orchestrator & Sub-Agent Architecture',                          questionText:"To what extent is the following true in your current practice: Complex tasks are handled by orchestrated multi-agent systems that plug into a shared internal platform - not individual engineers wiring up their own tools. Humans set the guardrails and escalation rules; agents handle execution and peer review within those rules." },
  { id:57, area:'Development',  subArea:'Technical Debt & Refactoring',              practice:'Code Quality Measurement & Governance',                          questionText:'To what extent does your team use AI for code quality measurement & governance?' },
  { id:58, area:'Development',  subArea:'Technical Debt & Refactoring',              practice:'Legacy code modernization',                                      questionText:'To what extent does your team use AI for legacy code modernization?' },
  { id:59, area:'Development',  subArea:'Technical Debt & Refactoring',              practice:'Refactoring Governance & Prioritization',                        questionText:'To what extent does your team use AI for refactoring governance & prioritization?' },
  { id:60, area:'Development',  subArea:'Technical Debt & Refactoring',              practice:'Technical debt identification',                                  questionText:'To what extent does your team use AI for technical debt identification?' },
  { id:61, area:'Development',  subArea:'Unit & Component Testing',                  practice:'Unit Test coverage',                                             questionText:'To what extent does your team use AI for unit test coverage?' },
  { id:62, area:'Development',  subArea:'Unit & Component Testing',                  practice:'Unit test execution',                                            questionText:'To what extent does your team use AI for unit test execution?' },
  { id:63, area:'Development',  subArea:'Unit & Component Testing',                  practice:'Unit test generation',                                           questionText:'To what extent does your team use AI for unit test generation?' },

  // Testing (38)
  { id:64,  area:'Testing', subArea:'Defect Management',          practice:'Bug reproducibility insights',                        questionText:'To what extent does your team use AI for bug reproducibility insights?' },
  { id:65,  area:'Testing', subArea:'Defect Management',          practice:'Defect Classification',                               questionText:'To what extent does your team use AI for defect classification?' },
  { id:66,  area:'Testing', subArea:'Defect Management',          practice:'Defect Triaging',                                     questionText:'To what extent does your team use AI for defect triaging?' },
  { id:67,  area:'Testing', subArea:'Defect Management',          practice:'Defect prioritization',                               questionText:'To what extent does your team use AI for defect prioritization?' },
  { id:68,  area:'Testing', subArea:'Defect Management',          practice:'Defect reporting',                                    questionText:'To what extent does your team use AI for defect reporting?' },
  { id:69,  area:'Testing', subArea:'Defect Management',          practice:'Defect resolution process',                           questionText:'To what extent does your team use AI for defect resolution process?' },
  { id:70,  area:'Testing', subArea:'Defect Management',          practice:'Defect tracking',                                     questionText:'To what extent does your team use AI for defect tracking?' },
  { id:71,  area:'Testing', subArea:'Defect Management',          practice:'Executive summary generation',                        questionText:'To what extent does your team use AI for executive summary generation?' },
  { id:72,  area:'Testing', subArea:'Test Automation Governance', practice:'CI integration for test automation',                  questionText:'To what extent does your team use AI for ci integration for test automation?' },
  { id:73,  area:'Testing', subArea:'Test Automation Governance', practice:'Test Automation Enablement & Governance',             questionText:'To what extent does your team use AI for test automation enablement & governance?' },
  { id:74,  area:'Testing', subArea:'Test Automation Governance', practice:'Test Script Lifecycle Management',                    questionText:'To what extent does your team use AI for test script lifecycle management?' },
  { id:75,  area:'Testing', subArea:'Test Automation Governance', practice:'Test automation strategy',                            questionText:'To what extent does your team use AI for test automation strategy?' },
  { id:76,  area:'Testing', subArea:'Test Design & Development',  practice:'Test Automation Architecture & Enablement',           questionText:'To what extent does your team use AI for test automation architecture & enablement?' },
  { id:77,  area:'Testing', subArea:'Test Design & Development',  practice:'Test Coverage',                                      questionText:'To what extent does your team use AI for test coverage?' },
  { id:78,  area:'Testing', subArea:'Test Design & Development',  practice:'Test Generation',                                    questionText:'To what extent does your team use AI for test generation?' },
  { id:79,  area:'Testing', subArea:'Test Design & Development',  practice:'Test Prioritization',                                questionText:'To what extent does your team use AI for test prioritization?' },
  { id:80,  area:'Testing', subArea:'Test Design & Development',  practice:'Test case development and traceability',              questionText:'To what extent does your team use AI for test case development and traceability?' },
  { id:81,  area:'Testing', subArea:'Test Design & Development',  practice:'Test data management',                               questionText:'To what extent does your team use AI for test data management?' },
  { id:82,  area:'Testing', subArea:'Test Execution & Reporting', practice:'Defect logging and triage',                          questionText:'To what extent does your team use AI for defect logging and triage?' },
  { id:83,  area:'Testing', subArea:'Test Execution & Reporting', practice:'Flaky test detection',                               questionText:'To what extent does your team use AI for flaky test detection?' },
  { id:84,  area:'Testing', subArea:'Test Execution & Reporting', practice:'Test Environment Scaling',                           questionText:'To what extent does your team use AI for test environment scaling?' },
  { id:85,  area:'Testing', subArea:'Test Execution & Reporting', practice:'Test Execution Reporting & Quality Insights',         questionText:'To what extent does your team use AI for test execution reporting & quality insights?' },
  { id:86,  area:'Testing', subArea:'Test Execution & Reporting', practice:'Test Quality Evidence & Insights Management',        questionText:'To what extent does your team use AI for test quality evidence & insights management?' },
  { id:87,  area:'Testing', subArea:'Test Execution & Reporting', practice:'Test Scripting',                                     questionText:'To what extent does your team use AI for test scripting?' },
  { id:88,  area:'Testing', subArea:'Test Execution & Reporting', practice:'Test Suite Optimization',                            questionText:'To what extent does your team use AI for test suite optimization?' },
  { id:89,  area:'Testing', subArea:'Test Execution & Reporting', practice:'Test environment management',                        questionText:'To what extent does your team use AI for test environment management?' },
  { id:90,  area:'Testing', subArea:'Test Execution & Reporting', practice:'Test execution planning & Orchestration',            questionText:'To what extent does your team use AI for test execution planning & orchestration?' },
  { id:91,  area:'Testing', subArea:'Test Strategy & Planning',   practice:'Define test objectives and scope',                   questionText:'To what extent does your team use AI for define test objectives and scope?' },
  { id:92,  area:'Testing', subArea:'Test Strategy & Planning',   practice:'Identify test types and levels',                     questionText:'To what extent does your team use AI for identify test types and levels?' },
  { id:93,  area:'Testing', subArea:'Test Strategy & Planning',   practice:'Resource and environment planning',                  questionText:'To what extent does your team use AI for resource and environment planning?' },
  { id:94,  area:'Testing', subArea:'Test Strategy & Planning',   practice:'Risk-based test prioritization',                     questionText:'To what extent does your team use AI for risk-based test prioritization?' },
  { id:95,  area:'Testing', subArea:'Testing',                    practice:'E2E Test Execution Workflow',                        questionText:"To what extent is the following true in your current practice: The system can block a bad change without a human clicking approve. Agents generate, run, and triage failures automatically. If a human must approve every test run result, the quality gate is not real." },
  { id:96,  area:'Testing', subArea:'Testing',                    practice:'Non-Functional & Performance Testing',               questionText:"To what extent is the following true in your current practice: SLA thresholds are set by the team; the agent enforces them on every change. Non-functional regressions are caught automatically - a human does not spot them in a periodic performance review." },
  { id:97,  area:'Testing', subArea:'Testing',                    practice:'Offline Evaluation of AI Features',                  questionText:"To what extent is the following true in your current practice: For any feature with an AI component, the agent runs structured evals against a golden dataset before code ships. The human sets the golden dataset and pass threshold once; the agent enforces it on every change." },
  { id:98,  area:'Testing', subArea:'Testing',                    practice:'Synthetic Test Data Creation',                       questionText:"To what extent is the following true in your current practice: The agent generates test data at scale from schema definitions and edge-case rules set by the engineer. A human does not curate or maintain test datasets manually - the agent produces them on demand." },
  { id:99,  area:'Testing', subArea:'Testing',                    practice:'Test Case Generation',                               questionText:"To what extent is the following true in your current practice: AI generates test cases from requirements covering happy paths, edge cases, and negative scenarios. A human reviews and selects which cases to use - the engineer does not write test cases from scratch." },
  { id:100, area:'Testing', subArea:'Testing',                    practice:'Test Script Generation',                             questionText:"To what extent is the following true in your current practice: Tests run automatically on every change - triggered by the pipeline, not by a human. The agent generates and executes scripts; a human reviews results and decides whether to proceed to the next stage." },
  { id:101, area:'Testing', subArea:'Testing',                    practice:'Vulnerability Simulation',                           questionText:"To what extent is the following true in your current practice: Adversarial probes and prompt injection tests run as part of every standard pipeline. Security regressions are caught by the system before anyone on the team notices - not by periodic manual pen testing." },

  // Deployment (19)
  { id:102, area:'Deployment', subArea:'CD / CI-CD',                        practice:'Automated Release Notes',                             questionText:"To what extent is the following true in your current practice: An agent generates release notes from commit history and PRs. The engineer approves before distribution - they do not write release notes by hand." },
  { id:103, area:'Deployment', subArea:'CD / CI-CD',                        practice:'Capacity Prediction',                                 questionText:"To what extent is the following true in your current practice: The system predicts capacity needs and triggers scaling recommendations before engineers react to a problem. If scaling decisions are made reactively by a human watching metrics, this is not Achieved." },
  { id:104, area:'Deployment', subArea:'CD / CI-CD',                        practice:'Deployment Script Generation',                        questionText:"To what extent is the following true in your current practice: AI generates deployment scripts, Helm charts, and YAML manifests. The engineer reviews and triggers deployment - they do not write deployment config from scratch." },
  { id:105, area:'Deployment', subArea:'CD / CI-CD',                        practice:'Initial Triage Assistance',                           questionText:"To what extent is the following true in your current practice: When something breaks in production, a system notices and surfaces probable causes before an engineer manually investigates. If an engineer is always the first to notice an incident, this practice is not Achieved." },
  { id:106, area:'Deployment', subArea:'CD / CI-CD',                        practice:'Root Cause Analysis (RCA)',                           questionText:"To what extent is the following true in your current practice: When something breaks, a system triages it and produces a structured RCA before a human investigates. The engineer validates and acts on the analysis - they do not start the investigation from raw logs." },
  { id:107, area:'Deployment', subArea:'CD / CI-CD',                        practice:'Runtime FinOps Optimisation',                         questionText:"To what extent is the following true in your current practice: The agent rightsizes resources and terminates idle instances automatically within cost thresholds the team has set. Cost is not managed by a human reviewing spend reports - the system optimises continuously." },
  { id:108, area:'Deployment', subArea:'CD / CI-CD',                        practice:'Self-Healing Systems',                                questionText:"To what extent is the following true in your current practice: When a service degrades, the system catches it, executes remediation, and - if the fix meets the defined guardrails - resolves it before anyone on the team knows it happened. Humans are pulled in only for ambiguous or high-risk incidents." },
  { id:109, area:'Deployment', subArea:'CI / CI-CD',                        practice:'AI-Integrated Quality Gates',                         questionText:"To what extent is the following true in your current practice: AI quality checks - linting, security scanning, coverage - run automatically on every commit. A human reads the results and decides whether to proceed. The checks run themselves; the human is still the gate." },
  { id:110, area:'Deployment', subArea:'CI / CI-CD',                        practice:'Agents Integrated in CI via API',                     questionText:"To what extent is the following true in your current practice: AI agents run as first-class CI pipeline steps via API, performing analysis and validation as part of the automated build. The agent acts in the pipeline; a human reviews output before merge." },
  { id:111, area:'Deployment', subArea:'CI / CI-CD',                        practice:'Code Quality, AI Slop & Data Lineage Reporting',      questionText:"To what extent is the following true in your current practice: The system blocks quality regressions and low-quality AI-generated code automatically on every pipeline run. A human does not periodically audit for code quality - the gate is always on." },
  { id:112, area:'Deployment', subArea:'CI / CI-CD',                        practice:'OSS, Deprecated Code & Evergreening Scans',           questionText:"To what extent is the following true in your current practice: Low-risk dependency updates and evergreening PRs ship automatically within guardrails the team has set. A human does not review every maintenance PR - the system handles routine updates and escalates only non-routine ones." },
  { id:113, area:'Deployment', subArea:'CI / CI-CD',                        practice:'Pipeline Creation Using AI',                          questionText:"To what extent is the following true in your current practice: An agent generates CI pipeline configuration from requirements. The engineer reviews and approves - they do not write YAML or pipeline scripts from scratch." },
  { id:114, area:'Deployment', subArea:'CI / CI-CD',                        practice:'Shift-Left Agents in Developer IDE',                  questionText:"To what extent is the following true in your current practice: The same agents that run in CI are available in the developer's IDE via a shared platform (MCP), not individually wired up by each engineer. Issues are caught before commit using the same rules as CI." },
  { id:115, area:'Deployment', subArea:'Continuous Integration & Delivery',  practice:'CI/CD Flow Optimization & Throughput Engineering',    questionText:'To what extent does your team use AI for ci/cd flow optimization & throughput engineering?' },
  { id:116, area:'Deployment', subArea:'Continuous Integration & Delivery',  practice:'Continuous Integration & Deployment Automation',      questionText:'To what extent does your team use AI for continuous integration & deployment automation?' },
  { id:117, area:'Deployment', subArea:'Continuous Integration & Delivery',  practice:'Pipeline Reliability Forecasting & Prevention',       questionText:'To what extent does your team use AI for pipeline reliability forecasting & prevention?' },
  { id:118, area:'Deployment', subArea:'Continuous Integration & Delivery',  practice:'Release Risk Assessment & Controls',                  questionText:'To what extent does your team use AI for release risk assessment & controls?' },
  { id:119, area:'Deployment', subArea:'Continuous Integration & Delivery',  practice:'Release Rollback & Recovery Management',              questionText:'To what extent does your team use AI for release rollback & recovery management?' },
  { id:120, area:'Deployment', subArea:'Continuous Integration & Delivery',  practice:'Release gating and approvals',                        questionText:'To what extent does your team use AI for release gating and approvals?' },
];

// ─── 10 AMS Questions ───────────────────────────────────────────────────────
const AMS_QUESTIONS = [
  { id:201, area:'Service Management',  subArea:'Service Catalogue & SLA Governance', practice:'AI-Driven SLA Monitoring & Alerting',      questionText:"To what extent is the following true in your current practice: SLA thresholds are monitored by an AI agent that alerts automatically before a breach occurs. A human does not poll dashboards to detect SLA risk — the system surfaces it proactively and triggers escalation." },
  { id:202, area:'Service Management',  subArea:'Service Request Automation',          practice:'Self-Service Request Fulfilment',           questionText:"To what extent does your team use AI to automatically classify, route, and fulfil service requests without human triage for routine requests? An agent handles standard requests end-to-end; a human only steps in for exceptions." },
  { id:203, area:'Incident Management', subArea:'Incident Triage & Classification',    practice:'AI-Powered Incident Triage',                questionText:"To what extent is the following true in your current practice: Every incoming incident is automatically classified, prioritised, and assigned by an AI agent based on historical patterns and impact scoring. A human does not perform initial triage — the agent does, and the human validates or overrides." },
  { id:204, area:'Incident Management', subArea:'Automated Runbook Execution',         practice:'Runbook Automation & Self-Healing',         questionText:"To what extent does your team use AI agents to execute runbooks automatically during incidents? The agent identifies the applicable runbook, executes remediation steps, and resolves the incident without human intervention for known failure modes." },
  { id:205, area:'Change Management',   subArea:'Change Risk Assessment',              practice:'AI-Driven Change Risk Scoring',             questionText:"To what extent is the following true in your current practice: Every change request is automatically risk-scored by an AI model before a human reviews it. The risk score, predicted blast radius, and conflict analysis are produced by the system — not estimated manually by the change manager." },
  { id:206, area:'Change Management',   subArea:'Change Impact Analysis',              practice:'Automated Conflict & Impact Detection',     questionText:"To what extent does your team use AI to automatically detect scheduling conflicts, downstream service impacts, and dependency risks for proposed changes? The agent produces an impact matrix; the change advisory board reviews AI output rather than building the analysis from scratch." },
  { id:207, area:'Problem Management',  subArea:'Root Cause Analysis Automation',      practice:'AI-Assisted Root Cause Analysis',           questionText:"To what extent is the following true in your current practice: When a problem record is raised, an AI agent automatically correlates related incidents, analyses log patterns, and produces a structured root cause hypothesis. The problem manager validates the AI output — they do not start analysis from raw data." },
  { id:208, area:'Problem Management',  subArea:'Proactive Problem Detection',         practice:'Predictive Anomaly & Problem Detection',    questionText:"To what extent does your team use AI to proactively detect emerging problems before they cause user-impacting incidents? An agent continuously analyses telemetry and raises problem records when anomaly patterns match known failure signatures — humans are not the first to notice degradation." },
  { id:209, area:'Release Management',  subArea:'Release Readiness Assessment',        practice:'AI-Powered Release Gate Assessment',        questionText:"To what extent is the following true in your current practice: An AI agent evaluates release readiness by aggregating test coverage, open defects, change risk scores, and deployment history into a structured go/no-go recommendation. The release manager reviews the AI recommendation — they do not compile the readiness evidence manually." },
  { id:210, area:'Release Management',  subArea:'Automated Release Orchestration',     practice:'End-to-End Release Pipeline Orchestration', questionText:"To what extent does your team use AI agents to orchestrate the end-to-end release pipeline — coordinating environment provisioning, smoke tests, approval workflows, and rollback triggers automatically? The release engineer sets guardrails and approves the final gate; the agent executes and monitors the pipeline." },
];

// ─── Seed ───────────────────────────────────────────────────────────────────
db.prepare('DELETE FROM questions').run();
console.log('✓ Cleared existing questions');

const insert = db.prepare(
  'INSERT INTO questions (id, framework, area, sub_area, practice, type, question_text) VALUES (?, ?, ?, ?, ?, ?, ?)'
);

const insertAll = db.transaction(() => {
  for (const q of SDLC_QUESTIONS) {
    insert.run(q.id, 'SDLC', q.area, q.subArea, q.practice, 'extent', q.questionText);
  }
  for (const q of AMS_QUESTIONS) {
    insert.run(q.id, 'AMS', q.area, q.subArea, q.practice, 'extent', q.questionText);
  }
});

insertAll();

console.log(`✓ Inserted ${SDLC_QUESTIONS.length} SDLC questions`);
console.log(`✓ Inserted ${AMS_QUESTIONS.length} AMS questions`);

// Summary
const summary = db.prepare("SELECT framework, area, COUNT(*) as cnt FROM questions GROUP BY framework, area ORDER BY framework, area").all();
console.log('\nQuestion distribution:');
summary.forEach(r => console.log(`  [${r.framework}] ${r.area}: ${r.cnt} questions`));
console.log('\n✓ Done!');
db.close();
